apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: task-service
  name: task-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: task-service
  template:
    metadata:
      labels:
        app: task-service
    spec:
      containers:
        - name: task-service
          image: mvermeulen/task-service
          ports:
            - containerPort: 8001
